/*
 * ITU Data
 *
 * Hello!!!
 *
 * API version: 1.0.0
 * Contact: alpha@bravo.charlie
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EnrolledCourse struct {

	CourseId int32 `json:"courseId,omitempty"`

	CourseName string `json:"courseName,omitempty"`

	// Hours worked each week
	Workload int32 `json:"workload,omitempty"`
}
