/*
 * ITU Data
 *
 * Hello!!!
 *
 * API version: 1.0.0
 * Contact: alpha@bravo.charlie
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Teacher struct {

	Id int32 `json:"id"`

	Name string `json:"name,omitempty"`

	Courses []int32 `json:"courses,omitempty"`

	Rating float32 `json:"rating,omitempty"`
}
