/*
 * ITU Data
 *
 * Hello!!!
 *
 * API version: 1.0.0
 * Contact: alpha@bravo.charlie
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Student struct {

	Id int32 `json:"id"`

	Initials string `json:"initials,omitempty"`

	Name string `json:"name,omitempty"`

	Enrollments []EnrolledCourse `json:"enrollments,omitempty"`
}
