/*
 * ITU Data
 *
 * Hello!!!
 *
 * API version: 1.0.0
 * Contact: alpha@bravo.charlie
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v2/",
		Index,
	},

	Route{
		"CourseCourseIdDelete",
		strings.ToUpper("Delete"),
		"/v2/course/{courseId}",
		CourseCourseIdDelete,
	},

	Route{
		"CourseCourseIdGet",
		strings.ToUpper("Get"),
		"/v2/course/{courseId}",
		CourseCourseIdGet,
	},

	Route{
		"CourseCourseIdPut",
		strings.ToUpper("Put"),
		"/v2/course/{courseId}",
		CourseCourseIdPut,
	},

	Route{
		"CoursePost",
		strings.ToUpper("Post"),
		"/v2/course",
		CoursePost,
	},
}
